import { App, TFile, TFolder, TAbstractFile } from "obsidian";
import type { CopilotSettings } from "./constants";

/**
 * Collects IDE state from the Obsidian API and generates a context
 * markdown string for Copilot CLI's copilot-instructions.md.
 */
export class ContextProvider {
  private app: App;
  private settings: CopilotSettings;
  private cachedVaultStructure: string = "";
  private vaultStructureDirty = true;

  // Persists last non-empty selection so it survives editor blur (e.g. clicking terminal)
  private lastSelection: { text: string; startLine: number; startCh: number; endLine: number; endCh: number; file: string } | null = null;

  constructor(app: App, settings: CopilotSettings) {
    this.app = app;
    this.settings = settings;
  }

  updateSettings(settings: CopilotSettings): void {
    this.settings = settings;
  }

  /** Mark vault structure cache as stale (called on file create/delete/rename) */
  invalidateVaultStructure(): void {
    this.vaultStructureDirty = true;
  }

  /** Clear the cached selection (e.g. when a new file is opened) */
  clearCachedSelection(): void {
    this.lastSelection = null;
  }

  /** Generate the full context markdown for copilot-instructions.md */
  generateContext(): string {
    const sections: string[] = [];

    sections.push("# Obsidian IDE Context");
    sections.push("");
    sections.push("This context is automatically generated by the Obsidian Copilot CLI plugin.");
    sections.push("It provides real-time IDE state so you can assist the user effectively.");
    sections.push("");

    // Active file
    const activeFileContext = this.getActiveFileContext();
    if (activeFileContext) {
      sections.push(activeFileContext);
    }

    // Open files
    if (this.settings.contextIncludeOpenFiles) {
      const openFilesContext = this.getOpenFilesContext();
      if (openFilesContext) {
        sections.push(openFilesContext);
      }
    }

    // Current selection
    const selectionContext = this.getSelectionContext();
    if (selectionContext) {
      sections.push(selectionContext);
    }

    // Active file metadata
    const metadataContext = this.getActiveFileMetadata();
    if (metadataContext) {
      sections.push(metadataContext);
    }

    // Vault structure
    if (this.settings.contextIncludeVaultStructure) {
      const vaultContext = this.getVaultStructureContext();
      if (vaultContext) {
        sections.push(vaultContext);
      }
    }

    return sections.join("\n");
  }

  /** Get active file path and optionally its content */
  private getActiveFileContext(): string | null {
    const file = this.app.workspace.getActiveFile();
    if (!file) return null;

    const lines: string[] = [];
    lines.push("## Active File");
    lines.push("");
    lines.push(`**Path:** \`${file.path}\``);
    lines.push(`**Name:** \`${file.name}\``);
    lines.push("");

    if (this.settings.contextIncludeFileContent) {
      const content = this.getFileContent(file);
      if (content !== null) {
        const truncated = content.length > this.settings.contextMaxFileSize;
        const displayContent = truncated
          ? content.slice(0, this.settings.contextMaxFileSize)
          : content;

        lines.push("### Content");
        lines.push("");
        lines.push("```markdown");
        lines.push(displayContent);
        lines.push("```");
        if (truncated) {
          lines.push("");
          lines.push(`> ⚠️ File truncated at ${this.settings.contextMaxFileSize} bytes (full size: ${content.length} bytes)`);
        }
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  /** Get list of currently open files in Obsidian */
  private getOpenFilesContext(): string | null {
    const openFiles: string[] = [];
    const activeFile = this.app.workspace.getActiveFile();

    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view?.getViewType() === "markdown") {
        const file = (leaf.view as any)?.file as TFile | undefined;
        if (file && !openFiles.includes(file.path)) {
          openFiles.push(file.path);
        }
      }
    });

    if (openFiles.length === 0) return null;

    const lines: string[] = [];
    lines.push("## Open Files");
    lines.push("");
    for (const path of openFiles) {
      const marker = activeFile && path === activeFile.path ? " ← active" : "";
      lines.push(`- \`${path}\`${marker}`);
    }
    lines.push("");

    return lines.join("\n");
  }

  /** Get current editor selection (falls back to last non-empty selection) */
  private getSelectionContext(): string | null {
    const editor = this.app.workspace.activeEditor?.editor;
    const activeFile = this.app.workspace.getActiveFile();

    // Try live selection first
    let selectionText: string | null = null;
    if (editor) {
      const live = editor.getSelection();
      if (live && live.trim().length > 0) {
        const from = editor.getCursor("from");
        const to = editor.getCursor("to");
        this.lastSelection = {
          text: live,
          startLine: from.line + 1,
          startCh: from.ch,
          endLine: to.line + 1,
          endCh: to.ch,
          file: activeFile?.path || "",
        };
        selectionText = live;
      }
    }

    // Fall back to cached selection
    if (!selectionText && this.lastSelection) {
      selectionText = this.lastSelection.text;
    }

    if (!selectionText || selectionText.trim().length === 0) return null;

    const truncated = selectionText.length > 2000;
    const displaySelection = truncated ? selectionText.slice(0, 2000) : selectionText;

    const lines: string[] = [];
    lines.push("## Current Selection");
    if (this.lastSelection && selectionText === this.lastSelection.text && this.lastSelection.file) {
      lines.push(`> In file: \`${this.lastSelection.file}\` (lines ${this.lastSelection.startLine}-${this.lastSelection.endLine})`);
    }
    lines.push("");
    lines.push("```");
    lines.push(displaySelection);
    lines.push("```");
    if (truncated) {
      lines.push("");
      lines.push(`> Selection truncated at 2000 chars (full: ${selectionText.length} chars)`);
    }
    lines.push("");

    return lines.join("\n");
  }

  /** Get frontmatter, tags, and links for the active file */
  private getActiveFileMetadata(): string | null {
    const file = this.app.workspace.getActiveFile();
    if (!file) return null;

    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache) return null;

    const lines: string[] = [];
    let hasContent = false;

    // Frontmatter
    if (cache.frontmatter) {
      hasContent = true;
      lines.push("## Active File Metadata");
      lines.push("");
      lines.push("### Frontmatter");
      lines.push("");
      lines.push("```yaml");
      for (const [key, value] of Object.entries(cache.frontmatter)) {
        if (key === "position") continue; // internal Obsidian field
        lines.push(`${key}: ${JSON.stringify(value)}`);
      }
      lines.push("```");
      lines.push("");
    }

    // Tags
    if (cache.tags && cache.tags.length > 0) {
      hasContent = true;
      if (!lines.some((l) => l.startsWith("## Active File Metadata"))) {
        lines.push("## Active File Metadata");
        lines.push("");
      }
      lines.push("### Tags");
      lines.push("");
      const tags = cache.tags.map((t) => t.tag);
      lines.push(tags.join(", "));
      lines.push("");
    }

    // Links
    if (cache.links && cache.links.length > 0) {
      hasContent = true;
      if (!lines.some((l) => l.startsWith("## Active File Metadata"))) {
        lines.push("## Active File Metadata");
        lines.push("");
      }
      lines.push("### Outgoing Links");
      lines.push("");
      for (const link of cache.links.slice(0, 20)) {
        lines.push(`- [[${link.link}]]`);
      }
      if (cache.links.length > 20) {
        lines.push(`- ... and ${cache.links.length - 20} more`);
      }
      lines.push("");
    }

    return hasContent ? lines.join("\n") : null;
  }

  /** Get vault structure as a tree (cached) */
  private getVaultStructureContext(): string | null {
    if (this.vaultStructureDirty) {
      this.cachedVaultStructure = this.buildVaultTree();
      this.vaultStructureDirty = false;
    }

    if (!this.cachedVaultStructure) return null;

    const lines: string[] = [];
    lines.push("## Vault Structure");
    lines.push("");
    lines.push("```");
    lines.push(this.cachedVaultStructure);
    lines.push("```");
    lines.push("");

    return lines.join("\n");
  }

  /** Build a tree representation of the vault (max depth 3, max 200 entries) */
  private buildVaultTree(): string {
    const lines: string[] = [];
    let count = 0;
    const maxEntries = 200;
    const maxDepth = 3;

    const walk = (folder: TFolder, depth: number, prefix: string): void => {
      if (count >= maxEntries || depth > maxDepth) return;

      const children = [...folder.children].sort((a, b) => {
        // Folders first, then files
        const aIsFolder = a instanceof TFolder ? 0 : 1;
        const bIsFolder = b instanceof TFolder ? 0 : 1;
        if (aIsFolder !== bIsFolder) return aIsFolder - bIsFolder;
        return a.name.localeCompare(b.name);
      });

      for (let i = 0; i < children.length && count < maxEntries; i++) {
        const child = children[i];
        const isLast = i === children.length - 1;
        const connector = isLast ? "└── " : "├── ";
        const nextPrefix = isLast ? prefix + "    " : prefix + "│   ";

        // Skip hidden files/folders (starting with .)
        if (child.name.startsWith(".")) continue;

        count++;
        if (child instanceof TFolder) {
          lines.push(`${prefix}${connector}${child.name}/`);
          walk(child, depth + 1, nextPrefix);
        } else {
          lines.push(`${prefix}${connector}${child.name}`);
        }
      }
    };

    const root = this.app.vault.getRoot();
    lines.push(root.name + "/");
    walk(root, 0, "");

    if (count >= maxEntries) {
      lines.push(`... (truncated at ${maxEntries} entries)`);
    }

    return lines.join("\n");
  }

  /** Synchronously read file content from the vault cache */
  private getFileContent(file: TFile): string | null {
    try {
      const cache = this.app.vault.getAbstractFileByPath(file.path);
      if (!cache || !(cache instanceof TFile)) return null;
      // Use cachedRead for sync-ish access — it reads from Obsidian's in-memory cache
      // We'll call the async version and cache the result
      return null; // Will be populated via async call in the writer
    } catch {
      return null;
    }
  }

  /** Generate JSON state object for MCP server consumption */
  generateStateJson(): Record<string, unknown> {
    const file = this.app.workspace.getActiveFile();
    const editor = this.app.workspace.activeEditor?.editor;

    // Open files
    const openFiles: string[] = [];
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view?.getViewType() === "markdown") {
        const f = (leaf.view as any)?.file as TFile | undefined;
        if (f && !openFiles.includes(f.path)) {
          openFiles.push(f.path);
        }
      }
    });

    // Selection — use live if available, fall back to cached
    let selection: Record<string, unknown> | null = null;
    if (editor) {
      const selText = editor.getSelection();
      if (selText && selText.trim().length > 0) {
        const from = editor.getCursor("from");
        const to = editor.getCursor("to");
        this.lastSelection = {
          text: selText,
          startLine: from.line + 1,
          startCh: from.ch,
          endLine: to.line + 1,
          endCh: to.ch,
          file: file?.path || "",
        };
        selection = {
          text: selText.length > 5000 ? selText.slice(0, 5000) : selText,
          startLine: from.line + 1,
          startCh: from.ch,
          endLine: to.line + 1,
          endCh: to.ch,
        };
      }
    }
    if (!selection && this.lastSelection) {
      selection = {
        text: this.lastSelection.text.length > 5000 ? this.lastSelection.text.slice(0, 5000) : this.lastSelection.text,
        startLine: this.lastSelection.startLine,
        startCh: this.lastSelection.startCh,
        endLine: this.lastSelection.endLine,
        endCh: this.lastSelection.endCh,
      };
    }

    // Metadata
    let metadata: Record<string, unknown> | null = null;
    if (file) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache) {
        metadata = {};
        if (cache.frontmatter) {
          const fm: Record<string, unknown> = {};
          for (const [key, value] of Object.entries(cache.frontmatter)) {
            if (key !== "position") fm[key] = value;
          }
          metadata.frontmatter = fm;
        }
        if (cache.tags && cache.tags.length > 0) {
          metadata.tags = cache.tags.map((t) => t.tag);
        }
        if (cache.links && cache.links.length > 0) {
          metadata.outgoingLinks = cache.links.map((l) => l.link);
        }
      }
    }

    // Vault path (from adapter)
    const vaultPath = (this.app.vault.adapter as any).basePath || "";

    return {
      activeFile: file ? file.path : null,
      selection,
      openFiles,
      vaultPath,
      metadata,
      timestamp: Date.now(),
    };
  }

  /** Async version: generate context with file content loaded */
  async generateContextAsync(): Promise<string> {
    const sections: string[] = [];

    sections.push("# Obsidian IDE Context");
    sections.push("");
    sections.push("This context is automatically generated by the Obsidian Copilot CLI plugin.");
    sections.push("It provides real-time IDE state so you can assist the user effectively.");
    sections.push("");

    // Active file with content
    const activeFileContext = await this.getActiveFileContextAsync();
    if (activeFileContext) {
      sections.push(activeFileContext);
    }

    // Open files
    if (this.settings.contextIncludeOpenFiles) {
      const openFilesContext = this.getOpenFilesContext();
      if (openFilesContext) {
        sections.push(openFilesContext);
      }
    }

    // Current selection
    const selectionContext = this.getSelectionContext();
    if (selectionContext) {
      sections.push(selectionContext);
    }

    // Active file metadata
    const metadataContext = this.getActiveFileMetadata();
    if (metadataContext) {
      sections.push(metadataContext);
    }

    // Vault structure
    if (this.settings.contextIncludeVaultStructure) {
      const vaultContext = this.getVaultStructureContext();
      if (vaultContext) {
        sections.push(vaultContext);
      }
    }

    return sections.join("\n");
  }

  /** Async active file context with content read from vault */
  private async getActiveFileContextAsync(): Promise<string | null> {
    const file = this.app.workspace.getActiveFile();
    if (!file) return null;

    const lines: string[] = [];
    lines.push("## Active File");
    lines.push("");
    lines.push(`**Path:** \`${file.path}\``);
    lines.push(`**Name:** \`${file.name}\``);
    lines.push("");

    if (this.settings.contextIncludeFileContent) {
      try {
        const content = await this.app.vault.cachedRead(file);
        if (content) {
          const truncated = content.length > this.settings.contextMaxFileSize;
          const displayContent = truncated
            ? content.slice(0, this.settings.contextMaxFileSize)
            : content;

          lines.push("### Content");
          lines.push("");
          lines.push("```markdown");
          lines.push(displayContent);
          lines.push("```");
          if (truncated) {
            lines.push("");
            lines.push(`> ⚠️ File truncated at ${this.settings.contextMaxFileSize} bytes (full size: ${content.length} bytes)`);
          }
          lines.push("");
        }
      } catch {
        // File not readable — skip content
      }
    }

    return lines.join("\n");
  }
}
